---
repos:
  - repo: local
    hooks:
      - id: check
        name: check
        entry: cargo check --all-targets
        language: system
        types: ["rust"]
        pass_filenames: false

      - id: clippy
        name: clippy
        entry: cargo clippy --all-targets
        language: system
        types: ["rust"]
        args: ["--"]
        pass_filenames: false

      - id: fmt
        name: fmt
        entry: cargo fmt
        language: system
        types: ["rust"]
        args: ["--"]

      - id: typos
        name: typos
        entry: typos
        language: system
        types: ["text"]
        pass_filenames: false
