[package]
name = "rust-basic-examples"
version = "0.1.0"
edition = "2021"

[dependencies]
ansi_term = "0.12.1"
clap = { version = "4.5.27", features = ["derive"] }
exitcode = "1.1.2"
iced = { version = "0.13.1", features = ["async-std"] }
indicatif = "0.17.9"
itertools = "0.14.0"
plotters = "0.3.7"
rand = "0.9.0"
rstest = "0.24.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"
tempfile = "3.16.0"
tokio = { version = "1.43.0", features = ["full"] }
tokio-postgres = "0.7.12"
ureq = { version = "3.0.2", features = ["json"] }
