[package]
name = "web"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.1"
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { version = "1.43.0", features = ["full"] }
ureq = { version = "3.0.2", features = ["json"] }
url = "2.5.4"
